### PR TITLE
⚙️ Update publish issue template to add confirm access right of package

### LINKED ISSUE #44: 💪 Update `publish` issue template to confirm published package concerning access right
# Details

* See → https://github.com/orgs/openreachtech/packages/npm/jest-expect-each/settings

```
□ Inherit access from source repository (recommended)
```

image

### PR DESCRIPTION
**Pull request by StewEucen**
# Why

* Close #44

### CODE REVIEW

**Review by arbredoux — APPROVED** [review]
⭐

**Review by EG-easy — APPROVED** [review]
🍵

**Review by hecticme — APPROVED** [review]
🙇‍♂️

**Review by JYama321 — APPROVED** [review]
Thanks！

**Review by Kinosuke-2503 — APPROVED** [review]
🚀

**Review by hieuthahn — APPROVED** [review]

**Review by hieuthahn — APPROVED** [review]
🚀

**Pull request merged**
